-- ============================================================
-- Quiniela Siths Mundial 2026
-- Crea la tabla `quinelas_siths` (NUEVA, vacia, propia de la Siths).
-- NO toca la tabla `quinelas` original (esa es de la quiniela de Tiza).
-- Ejecutar en: Supabase Dashboard -> SQL Editor -> New query -> Run
-- ============================================================

-- 1) Tabla
create table if not exists public.quinelas_siths (
  id          bigint generated by default as identity primary key,
  name        text not null,
  data        jsonb not null,
  created_at  timestamptz not null default now()
);

-- 2) Permitir acceso con la llave anon (igual que la tabla original)
alter table public.quinelas_siths enable row level security;

-- Lectura publica (admin y tabla leen todo)
create policy "quinelas_siths select" on public.quinelas_siths
  for select using (true);

-- Insercion publica (cada participante guarda su quiniela)
create policy "quinelas_siths insert" on public.quinelas_siths
  for insert with check (true);

-- Borrado publico (admin borra quinielas / resultados __real__)
create policy "quinelas_siths delete" on public.quinelas_siths
  for delete using (true);
